name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repositoryy
        uses: actions/checkout@v3

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Check spotless
        run: ./gradlew spotlessCheck

      - name: Check detekt
        run: ./gradlew detekt

  unit-test:
    needs: linter
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Generate test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit test results
          path: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false

  assemble:
    needs: linter
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs/apk

  android-test:
    needs: linter
    runs-on: macos-latest
    timeout-minutes: 45
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Setup AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Generate test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android test results
          path: '**/build/outputs/androidTest-results/connected/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false