name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Decode keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
          ENCODED_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          TMP_KEYSTORE_FILE_PATH=app/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_PROPERTIES | base64 -d > keystore.properties
          echo $ENCODED_KEYSTORE | base64 -d > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

      - name: Run unit test
        run: ./gradlew testReleaseUnitTest

      - name: Generate test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit test results
          path: '**/build/test-results/testReleaseUnitTest/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false

  android-test:
    runs-on: macos-latest
    timeout-minutes: 45
    strategy:
      matrix:
        api-level: [ 29 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Decode keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
          ENCODED_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          TMP_KEYSTORE_FILE_PATH=app/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_PROPERTIES | base64 -d > keystore.properties
          echo $ENCODED_KEYSTORE | base64 -d > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

      - name: Setup AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedReleaseAndroidTest -PtestBuildType=release

      - name: Generate test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Android test results
          path: '**/build/outputs/androidTest-results/connected/TEST-*.xml'
          reporter: java-junit
          fail-on-error: false

  release:
    needs: [unit-test, android-test]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: ./.github/workflows/gradle-cache
        with:
          encoded_local_properties: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Decode keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
          ENCODED_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: |
          TMP_KEYSTORE_FILE_PATH=app/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_PROPERTIES | base64 -d > keystore.properties
          echo $ENCODED_KEYSTORE | base64 -d > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: ./app/build/outputs/apk/release/*.apk
